version: '3.5'
services:
  app:
    container_name: one
    image: cedic/one:latest
    ports:
      - 3300:3000
    restart: unless-stopped
    networks:
      - one-network-registry-local
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-data:/docker-entrypoint-initdb.d
#      - ./docker-volumes/db/data:/var/lib/postgresql/data
#      - ./docker-volumes/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 5437:5432
    networks:
        - one-network-registry-local
volumes:
  postgres-data:

networks:
  one-network-registry-local:
    driver: bridge
