version: '3.5'
services:
  app:
    container_name: one
    image: cedic/one:latest
    ports:
      - 3300:3000
    restart: unless-stopped
    networks:
      - one-network-registry-local
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      # mount the volume to local directory /var/lib/docker/volumes
#      - postgres-data:/var/lib/postgresql/data
#      - postgres-data:/docker-entrypoint-initdb.d
      # mount the volume to local directory where docker-compose.yml is located
      - ./docker-volumes/db/data:/var/lib/postgresql/data
      - ./docker-volumes/db/sql:/docker-entrypoint-initdb.d
    privileged: true
    ports:
      - 5437:5432
    expose:
      - 5437
    networks:
        - one-network-registry-local
    command: bash -c "chown -R postgres:postgres /var/lib/postgresql/data && docker-entrypoint.sh postgres"

volumes:
  postgres-data:
    driver: local

networks:
  one-network-registry-local:
    driver: bridge
